version: '2.1'

x-defaults: &defaults
  restart: unless-stopped
  image: icyleafcn/zealot:nightly
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
  env_file: .env
  environment:
    ZEALOT_REDIS_HOST: redis
    ZEALOT_POSTGRES_HOST: postgres
  volumes:
    - zealot-data:/app

services:
  redis:
    image: redis:5-alpine
    command: redis-server
    volumes:
      - zealot-redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    image: postgres:12-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
