  web:
    container_name: zealot-web
    image: abiosoft/caddy:1.0.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./rootfs/etc/Caddyfile:/etc/Caddyfile
      - ./rootfs/etc/certs:/etc/certs
      - zealot-app:/app
      - zealot-data:/app/public/uploads
    env_file: .env
