
volumes:
  zealot-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: abc/zealot
  zealot-redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: abc/redis
  zealot-postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: abc/postgres
